# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170612_0327'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postlike',
            table=None,
        ),
    ]
