# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment_html_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(max_length=100)),
                ('youtube_videoId', models.CharField(max_length=100, unique=True)),
                ('youtube_title', models.CharField(max_length=100)),
                ('youtube_description', models.CharField(max_length=100)),
                ('youtube_thumbnails', models.CharField(max_length=100)),
            ],
        ),
    ]
