# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_description',
            field=models.TextField(blank=True),
        ),
    ]
